
# Site settings

title: Siko
email: s.popov@abv.bg
description: Wellcome Siko!
baseurl: "/Siko" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"
twitter_username: sikoPopov
github_username:  sikoPopov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - scss
  