
# Site settings

title: Siko
email: s.popov@abv.bg
description: Wellcome Siko!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: "docs"
twitter_username: sikoPopov
github_username:  sikoPopov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  - .vscode 
  
